require('vpryim.plugins')
require('vpryim.settings')
require('vpryim.colors')
require('vpryim.remap')
require('vpryim.p-mason')
require('vpryim.p-lsp')
require('vpryim.p-telescope')
require('vpryim.p-lualine')
