vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.wrap = false
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.scrolloff = 3
vim.opt.sidescrolloff = 3
vim.opt.termguicolors = true
vim.opt.background = 'light'
vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.signcolumn = 'number'
vim.opt.showmode = false
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.autoread = true
vim.opt.swapfile = false
-- vim.opt.title = true
-- vim.opt.colorcolumn = { 81, 101 }
